import { CardDetails, type Color, type Pattern, type Shape } from "$lib/types";
import seed from "seed-random";

const COMBINATIONS: [1 | 2 | 3, Color, Pattern, Shape][][] = [
  [
    [1, "purple", "outlined", "squiggle"],
    [2, "purple", "solid", "diamond"],
    [1, "purple", "striped", "diamond"],
    [3, "green", "solid", "squiggle"],
    [3, "green", "solid", "oval"],
    [1, "green", "solid", "oval"],
    [3, "green", "outlined", "squiggle"],
    [3, "purple", "striped", "squiggle"],
    [1, "red", "solid", "squiggle"],
    [2, "red", "solid", "oval"],
    [3, "red", "solid", "squiggle"],
    [2, "purple", "solid", "squiggle"],
  ],
  [
    [1, "red", "striped", "oval"],
    [1, "purple", "outlined", "diamond"],
    [2, "green", "outlined", "squiggle"],
    [1, "red", "striped", "squiggle"],
    [3, "green", "outlined", "squiggle"],
    [1, "green", "outlined", "squiggle"],
    [2, "red", "outlined", "oval"],
    [1, "green", "outlined", "diamond"],
    [1, "red", "outlined", "oval"],
    [2, "green", "striped", "squiggle"],
    [3, "purple", "striped", "diamond"],
    [3, "purple", "solid", "diamond"],
  ],
  [
    [2, "red", "outlined", "squiggle"],
    [1, "green", "solid", "oval"],
    [3, "green", "striped", "squiggle"],
    [3, "red", "solid", "diamond"],
    [2, "purple", "striped", "oval"],
    [3, "green", "striped", "oval"],
    [1, "red", "outlined", "diamond"],
    [1, "red", "solid", "diamond"],
    [3, "red", "striped", "oval"],
    [1, "purple", "solid", "squiggle"],
    [1, "green", "striped", "oval"],
    [1, "purple", "striped", "squiggle"],
  ],
  [
    [1, "purple", "outlined", "diamond"],
    [2, "red", "striped", "diamond"],
    [3, "purple", "striped", "oval"],
    [1, "green", "solid", "oval"],
    [2, "purple", "outlined", "oval"],
    [1, "red", "outlined", "diamond"],
    [3, "purple", "outlined", "diamond"],
    [3, "green", "outlined", "squiggle"],
    [2, "purple", "striped", "oval"],
    [3, "red", "solid", "diamond"],
    [1, "red", "striped", "squiggle"],
    [1, "green", "striped", "squiggle"],
  ],
  [
    [2, "red", "striped", "diamond"],
    [2, "green", "outlined", "diamond"],
    [3, "red", "solid", "diamond"],
    [3, "green", "outlined", "diamond"],
    [3, "red", "striped", "squiggle"],
    [2, "purple", "striped", "oval"],
    [2, "green", "striped", "oval"],
    [2, "red", "striped", "oval"],
    [2, "purple", "solid", "squiggle"],
    [3, "purple", "striped", "oval"],
    [1, "red", "solid", "squiggle"],
    [1, "purple", "striped", "diamond"],
  ],
  [
    [1, "purple", "outlined", "squiggle"],
    [1, "green", "striped", "squiggle"],
    [2, "green", "outlined", "oval"],
    [3, "green", "outlined", "diamond"],
    [2, "red", "striped", "squiggle"],
    [1, "green", "striped", "oval"],
    [2, "green", "solid", "oval"],
    [1, "purple", "outlined", "diamond"],
    [1, "green", "outlined", "squiggle"],
    [3, "red", "striped", "squiggle"],
    [3, "purple", "striped", "diamond"],
    [1, "red", "outlined", "squiggle"],
  ],
  [
    [3, "purple", "solid", "diamond"],
    [3, "red", "striped", "diamond"],
    [2, "red", "solid", "oval"],
    [1, "red", "outlined", "squiggle"],
    [2, "green", "striped", "oval"],
    [3, "green", "outlined", "diamond"],
    [3, "red", "striped", "squiggle"],
    [3, "red", "outlined", "oval"],
    [2, "green", "striped", "squiggle"],
    [2, "red", "solid", "squiggle"],
    [1, "red", "solid", "diamond"],
    [3, "red", "solid", "squiggle"],
  ],
  [
    [3, "purple", "striped", "diamond"],
    [2, "purple", "outlined", "oval"],
    [1, "purple", "outlined", "diamond"],
    [2, "red", "striped", "squiggle"],
    [2, "red", "outlined", "oval"],
    [2, "green", "outlined", "squiggle"],
    [1, "green", "outlined", "oval"],
    [3, "green", "outlined", "squiggle"],
    [3, "red", "striped", "diamond"],
    [1, "green", "solid", "squiggle"],
    [1, "purple", "solid", "squiggle"],
    [3, "red", "solid", "oval"],
  ],
  [
    [2, "red", "striped", "diamond"],
    [2, "red", "striped", "oval"],
    [1, "purple", "striped", "squiggle"],
    [2, "purple", "striped", "diamond"],
    [2, "green", "outlined", "squiggle"],
    [2, "green", "striped", "diamond"],
    [2, "purple", "striped", "squiggle"],
    [3, "purple", "striped", "squiggle"],
    [3, "purple", "solid", "diamond"],
    [2, "purple", "outlined", "squiggle"],
    [2, "green", "solid", "oval"],
    [1, "purple", "solid", "squiggle"],
  ],
  [
    [3, "green", "striped", "diamond"],
    [3, "green", "outlined", "oval"],
    [3, "green", "outlined", "diamond"],
    [1, "red", "solid", "oval"],
    [1, "red", "outlined", "squiggle"],
    [3, "red", "solid", "squiggle"],
    [1, "red", "solid", "squiggle"],
    [2, "purple", "solid", "squiggle"],
    [2, "purple", "outlined", "diamond"],
    [2, "purple", "outlined", "oval"],
    [1, "red", "outlined", "oval"],
    [2, "red", "striped", "squiggle"],
  ],
  [
    [1, "green", "striped", "oval"],
    [3, "red", "striped", "oval"],
    [3, "purple", "solid", "diamond"],
    [3, "purple", "outlined", "oval"],
    [3, "purple", "outlined", "diamond"],
    [3, "purple", "striped", "squiggle"],
    [3, "purple", "solid", "squiggle"],
    [2, "red", "striped", "oval"],
    [1, "green", "solid", "oval"],
    [1, "green", "outlined", "oval"],
    [2, "purple", "striped", "oval"],
    [2, "red", "outlined", "squiggle"],
  ],
  [
    [2, "green", "outlined", "oval"],
    [2, "purple", "solid", "squiggle"],
    [3, "green", "striped", "oval"],
    [1, "purple", "solid", "squiggle"],
    [3, "purple", "solid", "diamond"],
    [1, "green", "solid", "diamond"],
    [3, "green", "striped", "squiggle"],
    [1, "red", "solid", "oval"],
    [1, "green", "striped", "oval"],
    [3, "red", "solid", "squiggle"],
    [2, "red", "solid", "diamond"],
    [1, "red", "outlined", "diamond"],
  ],
  [
    [1, "red", "solid", "oval"],
    [1, "purple", "outlined", "oval"],
    [3, "green", "striped", "diamond"],
    [2, "green", "outlined", "diamond"],
    [2, "purple", "solid", "squiggle"],
    [3, "purple", "striped", "squiggle"],
    [2, "purple", "solid", "diamond"],
    [2, "red", "solid", "squiggle"],
    [3, "green", "solid", "diamond"],
    [2, "purple", "outlined", "squiggle"],
    [1, "green", "striped", "diamond"],
    [3, "green", "solid", "oval"],
  ],
  [
    [2, "green", "outlined", "oval"],
    [2, "green", "striped", "diamond"],
    [1, "red", "striped", "diamond"],
    [1, "red", "outlined", "diamond"],
    [1, "red", "outlined", "oval"],
    [2, "green", "solid", "oval"],
    [2, "purple", "solid", "squiggle"],
    [3, "purple", "solid", "squiggle"],
    [2, "purple", "outlined", "squiggle"],
    [1, "green", "solid", "diamond"],
    [1, "purple", "striped", "squiggle"],
    [1, "red", "solid", "diamond"],
  ],
  [
    [2, "green", "solid", "oval"],
    [1, "red", "striped", "squiggle"],
    [3, "red", "outlined", "diamond"],
    [1, "red", "solid", "squiggle"],
    [3, "green", "solid", "oval"],
    [2, "purple", "solid", "diamond"],
    [1, "red", "outlined", "squiggle"],
    [3, "purple", "outlined", "diamond"],
    [3, "green", "outlined", "diamond"],
    [1, "red", "outlined", "oval"],
    [2, "green", "outlined", "oval"],
    [2, "green", "outlined", "squiggle"],
  ],
  [
    [3, "red", "solid", "squiggle"],
    [1, "green", "outlined", "oval"],
    [2, "green", "solid", "diamond"],
    [2, "red", "solid", "oval"],
    [2, "purple", "outlined", "oval"],
    [2, "green", "striped", "diamond"],
    [3, "green", "striped", "squiggle"],
    [1, "green", "striped", "diamond"],
    [2, "green", "striped", "oval"],
    [3, "purple", "outlined", "oval"],
    [2, "red", "solid", "squiggle"],
    [3, "red", "striped", "squiggle"],
  ],
  [
    [1, "green", "outlined", "oval"],
    [3, "red", "outlined", "diamond"],
    [2, "red", "striped", "diamond"],
    [1, "red", "outlined", "diamond"],
    [1, "red", "striped", "diamond"],
    [2, "purple", "outlined", "diamond"],
    [1, "green", "outlined", "diamond"],
    [2, "purple", "outlined", "squiggle"],
    [1, "purple", "striped", "squiggle"],
    [1, "green", "outlined", "squiggle"],
    [3, "purple", "solid", "oval"],
    [2, "red", "striped", "squiggle"],
  ],
  [
    [2, "purple", "outlined", "oval"],
    [3, "red", "striped", "oval"],
    [1, "green", "outlined", "oval"],
    [1, "purple", "solid", "squiggle"],
    [3, "red", "striped", "diamond"],
    [2, "purple", "striped", "diamond"],
    [1, "purple", "striped", "diamond"],
    [1, "purple", "outlined", "oval"],
    [2, "green", "outlined", "diamond"],
    [2, "green", "striped", "diamond"],
    [2, "red", "striped", "diamond"],
    [3, "red", "outlined", "oval"],
  ],
  [
    [3, "green", "solid", "diamond"],
    [1, "green", "outlined", "squiggle"],
    [3, "purple", "striped", "oval"],
    [2, "purple", "solid", "oval"],
    [2, "green", "striped", "squiggle"],
    [2, "red", "striped", "diamond"],
    [3, "green", "striped", "diamond"],
    [1, "purple", "outlined", "diamond"],
    [1, "green", "solid", "oval"],
    [3, "red", "solid", "oval"],
    [1, "green", "striped", "squiggle"],
    [2, "red", "solid", "diamond"],
  ],
  [
    [2, "purple", "solid", "oval"],
    [2, "purple", "solid", "squiggle"],
    [1, "purple", "outlined", "oval"],
    [2, "purple", "outlined", "oval"],
    [3, "red", "solid", "oval"],
    [2, "green", "striped", "oval"],
    [3, "purple", "striped", "squiggle"],
    [1, "purple", "outlined", "diamond"],
    [3, "purple", "outlined", "squiggle"],
    [2, "red", "outlined", "oval"],
    [2, "green", "striped", "diamond"],
    [2, "red", "solid", "oval"],
  ],
  [
    [1, "green", "striped", "squiggle"],
    [1, "red", "striped", "oval"],
    [1, "purple", "solid", "diamond"],
    [3, "red", "striped", "oval"],
    [3, "green", "striped", "diamond"],
    [2, "red", "striped", "oval"],
    [3, "green", "striped", "oval"],
    [1, "purple", "striped", "oval"],
    [2, "purple", "outlined", "squiggle"],
    [2, "red", "striped", "diamond"],
    [1, "purple", "striped", "squiggle"],
    [2, "green", "striped", "oval"],
  ],
  [
    [1, "green", "solid", "oval"],
    [1, "purple", "outlined", "squiggle"],
    [1, "purple", "striped", "squiggle"],
    [1, "green", "outlined", "oval"],
    [2, "purple", "striped", "oval"],
    [3, "red", "outlined", "diamond"],
    [2, "green", "solid", "oval"],
    [1, "red", "outlined", "oval"],
    [2, "red", "outlined", "oval"],
    [1, "green", "solid", "squiggle"],
    [1, "green", "solid", "diamond"],
    [3, "red", "outlined", "squiggle"],
  ],
  [
    [3, "green", "outlined", "squiggle"],
    [2, "red", "solid", "oval"],
    [3, "green", "striped", "diamond"],
    [2, "green", "solid", "oval"],
    [3, "red", "solid", "diamond"],
    [1, "red", "solid", "squiggle"],
    [3, "purple", "outlined", "squiggle"],
    [1, "green", "striped", "diamond"],
    [3, "purple", "solid", "squiggle"],
    [2, "purple", "outlined", "squiggle"],
    [3, "purple", "striped", "squiggle"],
    [3, "red", "solid", "oval"],
  ],
  [
    [1, "green", "striped", "diamond"],
    [2, "purple", "outlined", "oval"],
    [2, "red", "outlined", "squiggle"],
    [2, "red", "striped", "oval"],
    [1, "purple", "striped", "diamond"],
    [3, "red", "solid", "squiggle"],
    [3, "purple", "solid", "oval"],
    [1, "red", "striped", "squiggle"],
    [3, "green", "outlined", "diamond"],
    [2, "green", "solid", "diamond"],
    [1, "red", "solid", "diamond"],
    [2, "green", "outlined", "diamond"],
  ],
  [
    [2, "purple", "outlined", "diamond"],
    [1, "green", "striped", "squiggle"],
    [2, "red", "outlined", "oval"],
    [1, "purple", "striped", "oval"],
    [3, "green", "solid", "squiggle"],
    [3, "green", "solid", "oval"],
    [3, "red", "solid", "squiggle"],
    [2, "purple", "striped", "squiggle"],
    [2, "green", "outlined", "squiggle"],
    [1, "red", "striped", "squiggle"],
    [2, "green", "striped", "diamond"],
    [2, "green", "outlined", "diamond"],
  ],
  [
    [2, "purple", "outlined", "oval"],
    [2, "purple", "outlined", "squiggle"],
    [1, "green", "solid", "diamond"],
    [2, "red", "striped", "squiggle"],
    [3, "purple", "solid", "oval"],
    [1, "purple", "solid", "oval"],
    [2, "green", "solid", "squiggle"],
    [3, "green", "solid", "oval"],
    [2, "purple", "outlined", "diamond"],
    [1, "red", "solid", "diamond"],
    [3, "red", "solid", "squiggle"],
    [2, "green", "solid", "diamond"],
  ],
  [
    [3, "green", "striped", "squiggle"],
    [3, "green", "solid", "squiggle"],
    [3, "red", "solid", "diamond"],
    [2, "purple", "solid", "oval"],
    [3, "purple", "outlined", "oval"],
    [1, "purple", "solid", "oval"],
    [3, "purple", "solid", "oval"],
    [1, "red", "solid", "diamond"],
    [1, "green", "solid", "diamond"],
    [1, "purple", "outlined", "diamond"],
    [1, "green", "outlined", "squiggle"],
    [1, "purple", "striped", "oval"],
  ],
  [
    [1, "red", "solid", "diamond"],
    [2, "purple", "outlined", "oval"],
    [3, "red", "outlined", "oval"],
    [2, "red", "striped", "oval"],
    [2, "red", "outlined", "diamond"],
    [3, "green", "striped", "diamond"],
    [1, "green", "solid", "diamond"],
    [1, "green", "outlined", "oval"],
    [1, "red", "outlined", "squiggle"],
    [3, "red", "solid", "diamond"],
    [1, "red", "solid", "squiggle"],
    [3, "purple", "outlined", "squiggle"],
  ],
  [
    [1, "red", "solid", "squiggle"],
    [3, "purple", "solid", "diamond"],
    [3, "purple", "outlined", "oval"],
    [3, "green", "solid", "diamond"],
    [1, "purple", "striped", "diamond"],
    [1, "green", "outlined", "oval"],
    [3, "green", "striped", "diamond"],
    [2, "purple", "solid", "oval"],
    [2, "red", "solid", "diamond"],
    [2, "green", "solid", "diamond"],
    [3, "red", "outlined", "diamond"],
    [1, "green", "solid", "diamond"],
  ],
  [
    [2, "purple", "striped", "oval"],
    [1, "purple", "striped", "squiggle"],
    [2, "purple", "outlined", "oval"],
    [2, "red", "striped", "squiggle"],
    [1, "red", "outlined", "squiggle"],
    [2, "red", "solid", "squiggle"],
    [2, "purple", "solid", "squiggle"],
    [3, "green", "striped", "oval"],
    [3, "green", "outlined", "squiggle"],
    [2, "purple", "solid", "diamond"],
    [3, "green", "outlined", "diamond"],
    [1, "red", "striped", "oval"],
  ],
  [
    [2, "red", "striped", "oval"],
    [3, "purple", "solid", "oval"],
    [1, "red", "solid", "squiggle"],
    [2, "purple", "striped", "squiggle"],
    [2, "purple", "solid", "diamond"],
    [3, "red", "striped", "squiggle"],
    [1, "green", "striped", "oval"],
    [1, "purple", "outlined", "diamond"],
    [3, "red", "striped", "diamond"],
    [3, "green", "outlined", "squiggle"],
    [1, "red", "outlined", "diamond"],
    [1, "purple", "solid", "diamond"],
  ],
  [
    [1, "green", "solid", "oval"],
    [3, "green", "outlined", "squiggle"],
    [3, "red", "striped", "squiggle"],
    [1, "green", "striped", "squiggle"],
    [2, "purple", "solid", "oval"],
    [3, "purple", "solid", "squiggle"],
    [1, "purple", "striped", "oval"],
    [3, "red", "striped", "oval"],
    [1, "red", "striped", "diamond"],
    [2, "purple", "outlined", "oval"],
    [1, "purple", "striped", "diamond"],
    [2, "red", "outlined", "squiggle"],
  ],
  [
    [3, "purple", "outlined", "squiggle"],
    [1, "purple", "striped", "oval"],
    [2, "green", "outlined", "diamond"],
    [3, "green", "outlined", "squiggle"],
    [3, "green", "striped", "oval"],
    [1, "purple", "solid", "diamond"],
    [1, "green", "solid", "squiggle"],
    [3, "red", "solid", "diamond"],
    [2, "purple", "solid", "diamond"],
    [2, "green", "solid", "diamond"],
    [2, "red", "striped", "squiggle"],
    [2, "purple", "outlined", "oval"],
  ],
  [
    [1, "red", "striped", "diamond"],
    [1, "green", "striped", "diamond"],
    [3, "red", "striped", "squiggle"],
    [3, "red", "outlined", "squiggle"],
    [1, "green", "outlined", "oval"],
    [1, "purple", "outlined", "oval"],
    [3, "purple", "solid", "squiggle"],
    [2, "green", "solid", "diamond"],
    [2, "green", "outlined", "oval"],
    [3, "green", "solid", "squiggle"],
    [2, "purple", "striped", "diamond"],
    [3, "green", "striped", "squiggle"],
  ],
  [
    [2, "purple", "striped", "squiggle"],
    [3, "red", "outlined", "diamond"],
    [3, "red", "striped", "oval"],
    [2, "green", "outlined", "diamond"],
    [2, "green", "striped", "squiggle"],
    [1, "purple", "solid", "squiggle"],
    [1, "purple", "outlined", "diamond"],
    [1, "green", "striped", "diamond"],
    [1, "purple", "solid", "oval"],
    [2, "red", "striped", "squiggle"],
    [2, "purple", "solid", "diamond"],
    [1, "green", "solid", "squiggle"],
  ],
  [
    [3, "red", "solid", "oval"],
    [2, "purple", "outlined", "oval"],
    [1, "purple", "striped", "diamond"],
    [2, "green", "outlined", "diamond"],
    [1, "purple", "outlined", "oval"],
    [3, "purple", "solid", "diamond"],
    [2, "red", "striped", "diamond"],
    [2, "green", "outlined", "squiggle"],
    [2, "green", "striped", "squiggle"],
    [3, "red", "solid", "diamond"],
    [1, "green", "outlined", "diamond"],
    [3, "green", "solid", "squiggle"],
  ],
  [
    [1, "green", "outlined", "oval"],
    [2, "green", "striped", "squiggle"],
    [3, "red", "striped", "diamond"],
    [2, "red", "outlined", "oval"],
    [1, "red", "outlined", "diamond"],
    [1, "purple", "striped", "oval"],
    [3, "purple", "outlined", "oval"],
    [3, "purple", "outlined", "diamond"],
    [3, "green", "solid", "oval"],
    [3, "purple", "striped", "squiggle"],
    [3, "red", "striped", "oval"],
    [3, "green", "solid", "squiggle"],
  ],
  [
    [1, "purple", "outlined", "squiggle"],
    [3, "green", "outlined", "oval"],
    [1, "purple", "striped", "squiggle"],
    [2, "green", "solid", "squiggle"],
    [2, "red", "outlined", "squiggle"],
    [2, "green", "solid", "oval"],
    [2, "purple", "striped", "oval"],
    [3, "green", "solid", "squiggle"],
    [1, "red", "outlined", "diamond"],
    [1, "purple", "outlined", "diamond"],
    [2, "green", "solid", "diamond"],
    [1, "purple", "outlined", "oval"],
  ],
  [
    [3, "red", "outlined", "diamond"],
    [2, "red", "solid", "squiggle"],
    [1, "purple", "striped", "diamond"],
    [2, "red", "striped", "squiggle"],
    [3, "red", "striped", "squiggle"],
    [3, "red", "solid", "oval"],
    [3, "green", "solid", "squiggle"],
    [3, "purple", "striped", "diamond"],
    [1, "red", "outlined", "diamond"],
    [3, "purple", "solid", "oval"],
    [2, "purple", "striped", "diamond"],
    [1, "green", "solid", "diamond"],
  ],
  [
    [2, "green", "solid", "oval"],
    [2, "purple", "solid", "squiggle"],
    [1, "purple", "solid", "oval"],
    [3, "purple", "striped", "squiggle"],
    [3, "green", "outlined", "squiggle"],
    [2, "purple", "outlined", "oval"],
    [3, "purple", "outlined", "diamond"],
    [3, "purple", "solid", "squiggle"],
    [2, "red", "solid", "diamond"],
    [1, "purple", "solid", "diamond"],
    [1, "purple", "solid", "squiggle"],
    [1, "green", "striped", "diamond"],
  ],
  [
    [1, "green", "outlined", "diamond"],
    [2, "red", "striped", "oval"],
    [3, "red", "striped", "oval"],
    [3, "green", "solid", "squiggle"],
    [2, "red", "solid", "oval"],
    [3, "purple", "striped", "squiggle"],
    [1, "green", "striped", "squiggle"],
    [3, "purple", "solid", "squiggle"],
    [2, "green", "solid", "diamond"],
    [1, "green", "solid", "oval"],
    [3, "purple", "outlined", "diamond"],
    [2, "red", "solid", "squiggle"],
  ],
  [
    [1, "green", "striped", "squiggle"],
    [1, "purple", "solid", "squiggle"],
    [3, "purple", "solid", "squiggle"],
    [1, "purple", "outlined", "diamond"],
    [2, "purple", "striped", "squiggle"],
    [1, "red", "solid", "oval"],
    [1, "green", "striped", "diamond"],
    [2, "green", "solid", "diamond"],
    [1, "green", "solid", "diamond"],
    [3, "purple", "outlined", "oval"],
    [2, "purple", "outlined", "squiggle"],
    [2, "purple", "solid", "squiggle"],
  ],
  [
    [3, "purple", "solid", "diamond"],
    [3, "green", "outlined", "squiggle"],
    [2, "green", "striped", "squiggle"],
    [3, "red", "striped", "oval"],
    [3, "purple", "solid", "oval"],
    [1, "red", "outlined", "oval"],
    [1, "purple", "striped", "oval"],
    [3, "green", "solid", "oval"],
    [2, "green", "striped", "diamond"],
    [3, "red", "striped", "diamond"],
    [3, "purple", "striped", "diamond"],
    [3, "green", "striped", "diamond"],
  ],
  [
    [2, "red", "solid", "oval"],
    [3, "purple", "striped", "diamond"],
    [2, "green", "striped", "squiggle"],
    [3, "purple", "outlined", "squiggle"],
    [2, "purple", "striped", "squiggle"],
    [3, "purple", "solid", "diamond"],
    [3, "purple", "solid", "oval"],
    [2, "green", "outlined", "diamond"],
    [3, "green", "outlined", "diamond"],
    [2, "purple", "outlined", "squiggle"],
    [1, "red", "outlined", "oval"],
    [1, "red", "striped", "squiggle"],
  ],
  [
    [1, "green", "outlined", "oval"],
    [3, "red", "outlined", "oval"],
    [1, "green", "outlined", "diamond"],
    [3, "green", "outlined", "oval"],
    [3, "purple", "solid", "diamond"],
    [1, "green", "striped", "diamond"],
    [2, "red", "outlined", "diamond"],
    [3, "red", "striped", "squiggle"],
    [1, "red", "outlined", "squiggle"],
    [3, "red", "striped", "oval"],
    [1, "purple", "solid", "oval"],
    [2, "green", "outlined", "oval"],
  ],
  [
    [3, "green", "solid", "diamond"],
    [3, "green", "striped", "squiggle"],
    [2, "purple", "outlined", "diamond"],
    [3, "red", "striped", "oval"],
    [1, "red", "striped", "diamond"],
    [1, "red", "striped", "oval"],
    [3, "red", "solid", "diamond"],
    [1, "green", "solid", "squiggle"],
    [1, "red", "striped", "squiggle"],
    [1, "red", "solid", "oval"],
    [3, "purple", "outlined", "oval"],
    [1, "green", "striped", "diamond"],
  ],
  [
    [3, "purple", "solid", "diamond"],
    [3, "red", "solid", "squiggle"],
    [3, "purple", "striped", "oval"],
    [2, "purple", "solid", "diamond"],
    [1, "red", "striped", "squiggle"],
    [2, "red", "outlined", "squiggle"],
    [2, "purple", "solid", "oval"],
    [3, "purple", "outlined", "oval"],
    [2, "red", "striped", "squiggle"],
    [1, "green", "striped", "oval"],
    [2, "red", "solid", "squiggle"],
    [1, "green", "solid", "diamond"],
  ],
  [
    [2, "red", "outlined", "diamond"],
    [3, "red", "striped", "squiggle"],
    [2, "green", "outlined", "oval"],
    [1, "purple", "solid", "squiggle"],
    [3, "purple", "outlined", "squiggle"],
    [1, "red", "outlined", "diamond"],
    [3, "purple", "solid", "diamond"],
    [3, "red", "outlined", "squiggle"],
    [2, "green", "striped", "diamond"],
    [3, "green", "striped", "oval"],
    [3, "purple", "striped", "diamond"],
    [1, "green", "outlined", "oval"],
  ],
  [
    [2, "red", "striped", "squiggle"],
    [2, "red", "solid", "squiggle"],
    [2, "green", "solid", "diamond"],
    [3, "purple", "solid", "diamond"],
    [3, "green", "striped", "squiggle"],
    [1, "red", "solid", "diamond"],
    [1, "red", "striped", "oval"],
    [2, "purple", "striped", "diamond"],
    [2, "red", "outlined", "squiggle"],
    [2, "red", "outlined", "diamond"],
    [2, "green", "solid", "oval"],
    [3, "purple", "solid", "squiggle"],
  ],
  [
    [2, "green", "solid", "oval"],
    [1, "green", "striped", "squiggle"],
    [1, "purple", "outlined", "squiggle"],
    [3, "red", "solid", "squiggle"],
    [3, "red", "striped", "squiggle"],
    [3, "purple", "striped", "oval"],
    [2, "red", "solid", "diamond"],
    [1, "green", "outlined", "squiggle"],
    [2, "purple", "solid", "squiggle"],
    [1, "red", "outlined", "oval"],
    [3, "purple", "solid", "squiggle"],
    [3, "purple", "outlined", "diamond"],
  ],
  [
    [2, "green", "outlined", "squiggle"],
    [1, "purple", "striped", "diamond"],
    [3, "red", "striped", "diamond"],
    [1, "green", "outlined", "oval"],
    [1, "purple", "outlined", "oval"],
    [3, "green", "outlined", "diamond"],
    [1, "green", "outlined", "squiggle"],
    [1, "red", "outlined", "diamond"],
    [3, "purple", "striped", "squiggle"],
    [1, "green", "outlined", "diamond"],
    [2, "purple", "outlined", "diamond"],
    [3, "red", "outlined", "diamond"],
  ],
  [
    [1, "red", "outlined", "diamond"],
    [3, "purple", "striped", "oval"],
    [1, "green", "outlined", "diamond"],
    [1, "red", "outlined", "squiggle"],
    [2, "red", "solid", "diamond"],
    [2, "purple", "outlined", "oval"],
    [2, "green", "striped", "squiggle"],
    [3, "red", "striped", "squiggle"],
    [3, "green", "outlined", "diamond"],
    [1, "purple", "solid", "oval"],
    [1, "green", "solid", "oval"],
    [1, "red", "outlined", "oval"],
  ],
  [
    [3, "red", "outlined", "diamond"],
    [2, "purple", "outlined", "oval"],
    [3, "green", "solid", "squiggle"],
    [2, "green", "striped", "oval"],
    [1, "green", "outlined", "oval"],
    [3, "purple", "striped", "squiggle"],
    [1, "red", "striped", "diamond"],
    [2, "red", "outlined", "squiggle"],
    [2, "purple", "striped", "diamond"],
    [2, "purple", "solid", "diamond"],
    [2, "red", "solid", "squiggle"],
    [1, "purple", "solid", "squiggle"],
  ],
  [
    [2, "red", "striped", "oval"],
    [2, "green", "solid", "squiggle"],
    [2, "red", "outlined", "diamond"],
    [2, "purple", "striped", "oval"],
    [1, "purple", "solid", "squiggle"],
    [1, "purple", "outlined", "diamond"],
    [1, "purple", "outlined", "squiggle"],
    [2, "red", "striped", "squiggle"],
    [3, "purple", "solid", "squiggle"],
    [3, "green", "solid", "squiggle"],
    [2, "green", "striped", "oval"],
    [2, "purple", "striped", "diamond"],
  ],
  [
    [2, "red", "outlined", "oval"],
    [3, "green", "striped", "diamond"],
    [2, "purple", "solid", "squiggle"],
    [2, "purple", "outlined", "oval"],
    [2, "green", "outlined", "squiggle"],
    [3, "green", "solid", "oval"],
    [3, "red", "outlined", "diamond"],
    [2, "red", "outlined", "diamond"],
    [3, "red", "striped", "squiggle"],
    [3, "green", "striped", "squiggle"],
    [1, "purple", "solid", "squiggle"],
    [1, "red", "solid", "diamond"],
  ],
  [
    [2, "red", "striped", "diamond"],
    [2, "purple", "outlined", "oval"],
    [2, "red", "solid", "diamond"],
    [3, "green", "solid", "oval"],
    [2, "red", "solid", "squiggle"],
    [1, "green", "solid", "squiggle"],
    [3, "red", "solid", "diamond"],
    [1, "purple", "solid", "squiggle"],
    [3, "green", "striped", "diamond"],
    [2, "purple", "solid", "squiggle"],
    [1, "purple", "striped", "diamond"],
    [3, "purple", "solid", "squiggle"],
  ],
  [
    [2, "green", "outlined", "squiggle"],
    [3, "red", "striped", "oval"],
    [1, "green", "outlined", "diamond"],
    [2, "red", "outlined", "diamond"],
    [3, "red", "striped", "diamond"],
    [1, "green", "solid", "squiggle"],
    [3, "purple", "solid", "squiggle"],
    [1, "green", "striped", "oval"],
    [2, "purple", "outlined", "diamond"],
    [1, "purple", "solid", "squiggle"],
    [3, "purple", "striped", "oval"],
    [2, "red", "outlined", "oval"],
  ],
  [
    [3, "green", "outlined", "diamond"],
    [2, "green", "outlined", "oval"],
    [3, "green", "solid", "oval"],
    [2, "red", "outlined", "diamond"],
    [1, "green", "outlined", "oval"],
    [3, "green", "outlined", "squiggle"],
    [2, "red", "striped", "squiggle"],
    [1, "green", "solid", "squiggle"],
    [3, "red", "outlined", "oval"],
    [2, "green", "striped", "oval"],
    [1, "purple", "outlined", "oval"],
    [3, "green", "outlined", "oval"],
  ],
  [
    [3, "red", "solid", "oval"],
    [2, "red", "outlined", "oval"],
    [1, "red", "striped", "squiggle"],
    [3, "green", "outlined", "diamond"],
    [2, "green", "striped", "diamond"],
    [3, "purple", "solid", "squiggle"],
    [1, "purple", "outlined", "squiggle"],
    [2, "purple", "striped", "diamond"],
    [3, "purple", "striped", "squiggle"],
    [1, "green", "striped", "squiggle"],
    [3, "green", "striped", "oval"],
    [1, "green", "outlined", "squiggle"],
  ],
  [
    [3, "green", "striped", "oval"],
    [3, "purple", "outlined", "squiggle"],
    [2, "red", "striped", "oval"],
    [1, "red", "outlined", "oval"],
    [1, "green", "solid", "diamond"],
    [3, "red", "solid", "oval"],
    [3, "red", "striped", "diamond"],
    [3, "purple", "striped", "squiggle"],
    [1, "green", "striped", "diamond"],
    [1, "purple", "solid", "squiggle"],
    [2, "green", "outlined", "oval"],
    [1, "purple", "outlined", "squiggle"],
  ],
  [
    [2, "purple", "striped", "diamond"],
    [1, "purple", "outlined", "oval"],
    [2, "purple", "striped", "oval"],
    [1, "purple", "outlined", "diamond"],
    [2, "red", "striped", "diamond"],
    [1, "purple", "outlined", "squiggle"],
    [2, "green", "outlined", "diamond"],
    [2, "red", "solid", "squiggle"],
    [2, "red", "solid", "diamond"],
    [2, "red", "outlined", "diamond"],
    [3, "green", "striped", "diamond"],
    [3, "red", "striped", "squiggle"],
  ],
  [
    [3, "red", "solid", "diamond"],
    [1, "purple", "solid", "squiggle"],
    [3, "red", "striped", "oval"],
    [1, "red", "striped", "squiggle"],
    [3, "green", "striped", "diamond"],
    [2, "red", "striped", "diamond"],
    [3, "red", "outlined", "diamond"],
    [1, "green", "outlined", "squiggle"],
    [1, "purple", "outlined", "diamond"],
    [2, "green", "outlined", "diamond"],
    [1, "red", "outlined", "squiggle"],
    [1, "purple", "striped", "diamond"],
  ],
  [
    [3, "green", "solid", "oval"],
    [1, "purple", "striped", "diamond"],
    [3, "red", "solid", "oval"],
    [1, "purple", "solid", "squiggle"],
    [2, "red", "solid", "squiggle"],
    [2, "green", "solid", "oval"],
    [3, "red", "solid", "diamond"],
    [1, "green", "outlined", "diamond"],
    [2, "red", "outlined", "squiggle"],
    [3, "purple", "outlined", "oval"],
    [2, "purple", "striped", "diamond"],
    [1, "red", "outlined", "diamond"],
  ],
  [
    [3, "red", "solid", "diamond"],
    [2, "green", "striped", "squiggle"],
    [1, "green", "striped", "oval"],
    [1, "purple", "outlined", "squiggle"],
    [1, "purple", "striped", "oval"],
    [2, "green", "striped", "oval"],
    [2, "green", "outlined", "squiggle"],
    [2, "red", "outlined", "squiggle"],
    [3, "red", "outlined", "squiggle"],
    [3, "green", "outlined", "oval"],
    [3, "purple", "outlined", "squiggle"],
    [2, "purple", "solid", "diamond"],
  ],
  [
    [1, "red", "outlined", "oval"],
    [1, "purple", "striped", "diamond"],
    [2, "green", "solid", "diamond"],
    [1, "red", "outlined", "squiggle"],
    [2, "purple", "solid", "oval"],
    [2, "red", "striped", "oval"],
    [3, "green", "outlined", "oval"],
    [2, "purple", "outlined", "oval"],
    [3, "green", "striped", "diamond"],
    [2, "red", "solid", "squiggle"],
    [3, "red", "outlined", "diamond"],
    [2, "purple", "striped", "oval"],
  ],
  [
    [3, "purple", "solid", "oval"],
    [3, "red", "solid", "oval"],
    [2, "green", "striped", "squiggle"],
    [1, "green", "outlined", "diamond"],
    [3, "red", "striped", "diamond"],
    [3, "purple", "outlined", "diamond"],
    [3, "red", "outlined", "oval"],
    [1, "red", "outlined", "diamond"],
    [3, "purple", "striped", "squiggle"],
    [3, "purple", "solid", "diamond"],
    [3, "red", "solid", "squiggle"],
    [3, "green", "solid", "oval"],
  ],
  [
    [1, "green", "solid", "squiggle"],
    [2, "purple", "striped", "oval"],
    [3, "purple", "outlined", "diamond"],
    [2, "green", "solid", "diamond"],
    [1, "green", "striped", "diamond"],
    [3, "purple", "striped", "squiggle"],
    [3, "red", "outlined", "squiggle"],
    [3, "green", "solid", "oval"],
    [2, "red", "striped", "diamond"],
    [3, "red", "outlined", "diamond"],
    [2, "red", "striped", "oval"],
    [1, "green", "striped", "oval"],
  ],
  [
    [1, "purple", "striped", "oval"],
    [2, "purple", "solid", "oval"],
    [2, "purple", "striped", "squiggle"],
    [2, "red", "striped", "oval"],
    [1, "purple", "solid", "squiggle"],
    [2, "green", "outlined", "oval"],
    [2, "purple", "outlined", "diamond"],
    [3, "purple", "outlined", "squiggle"],
    [2, "purple", "solid", "diamond"],
    [2, "purple", "solid", "squiggle"],
    [3, "green", "outlined", "squiggle"],
    [2, "green", "outlined", "diamond"],
  ],
  [
    [3, "purple", "solid", "squiggle"],
    [1, "purple", "striped", "diamond"],
    [1, "red", "striped", "oval"],
    [2, "red", "outlined", "squiggle"],
    [2, "green", "solid", "diamond"],
    [3, "red", "solid", "diamond"],
    [3, "green", "striped", "squiggle"],
    [3, "green", "solid", "oval"],
    [2, "purple", "solid", "oval"],
    [1, "purple", "outlined", "oval"],
    [3, "red", "striped", "squiggle"],
    [1, "green", "striped", "squiggle"],
  ],
  [
    [1, "green", "solid", "squiggle"],
    [2, "purple", "striped", "diamond"],
    [3, "red", "outlined", "oval"],
    [3, "purple", "solid", "diamond"],
    [3, "red", "striped", "oval"],
    [3, "purple", "outlined", "oval"],
    [2, "purple", "outlined", "diamond"],
    [2, "green", "solid", "diamond"],
    [1, "purple", "outlined", "squiggle"],
    [1, "red", "solid", "diamond"],
    [1, "red", "outlined", "squiggle"],
    [2, "red", "solid", "oval"],
  ],
  [
    [2, "red", "solid", "squiggle"],
    [1, "red", "solid", "squiggle"],
    [2, "red", "striped", "oval"],
    [3, "green", "striped", "squiggle"],
    [1, "green", "striped", "squiggle"],
    [3, "purple", "solid", "squiggle"],
    [3, "red", "outlined", "squiggle"],
    [2, "purple", "outlined", "squiggle"],
    [1, "red", "striped", "diamond"],
    [2, "purple", "striped", "oval"],
    [2, "red", "outlined", "squiggle"],
    [3, "red", "striped", "squiggle"],
  ],
  [
    [1, "green", "striped", "oval"],
    [1, "green", "solid", "oval"],
    [3, "green", "striped", "diamond"],
    [2, "red", "solid", "diamond"],
    [3, "purple", "solid", "diamond"],
    [2, "purple", "outlined", "squiggle"],
    [2, "red", "outlined", "squiggle"],
    [1, "purple", "outlined", "diamond"],
    [2, "green", "outlined", "squiggle"],
    [1, "green", "solid", "diamond"],
    [1, "red", "striped", "diamond"],
    [2, "green", "solid", "squiggle"],
  ],
  [
    [3, "purple", "striped", "squiggle"],
    [2, "purple", "outlined", "diamond"],
    [2, "red", "outlined", "squiggle"],
    [2, "green", "solid", "squiggle"],
    [3, "green", "solid", "oval"],
    [1, "green", "solid", "diamond"],
    [2, "purple", "striped", "squiggle"],
    [2, "green", "solid", "diamond"],
    [3, "red", "outlined", "diamond"],
    [3, "green", "solid", "diamond"],
    [1, "purple", "striped", "diamond"],
    [3, "green", "striped", "oval"],
  ],
  [
    [1, "purple", "outlined", "oval"],
    [3, "green", "outlined", "oval"],
    [1, "purple", "solid", "oval"],
    [1, "purple", "striped", "oval"],
    [1, "green", "solid", "squiggle"],
    [1, "green", "striped", "diamond"],
    [1, "green", "outlined", "oval"],
    [1, "red", "solid", "squiggle"],
    [1, "purple", "striped", "diamond"],
    [2, "red", "outlined", "diamond"],
    [1, "red", "striped", "squiggle"],
    [3, "purple", "solid", "diamond"],
  ],
  [
    [1, "red", "outlined", "diamond"],
    [1, "green", "solid", "oval"],
    [3, "red", "striped", "oval"],
    [2, "red", "outlined", "oval"],
    [3, "purple", "striped", "squiggle"],
    [2, "green", "solid", "oval"],
    [3, "purple", "solid", "diamond"],
    [3, "red", "outlined", "squiggle"],
    [1, "red", "solid", "squiggle"],
    [2, "red", "outlined", "squiggle"],
    [2, "red", "outlined", "diamond"],
    [3, "green", "outlined", "diamond"],
  ],
  [
    [2, "purple", "outlined", "diamond"],
    [2, "red", "outlined", "diamond"],
    [2, "purple", "solid", "diamond"],
    [2, "purple", "striped", "diamond"],
    [2, "green", "striped", "diamond"],
    [1, "purple", "outlined", "oval"],
    [2, "red", "solid", "diamond"],
    [3, "purple", "solid", "diamond"],
    [1, "purple", "striped", "oval"],
    [3, "purple", "solid", "oval"],
    [1, "purple", "striped", "diamond"],
    [1, "purple", "solid", "squiggle"],
  ],
  [
    [1, "red", "solid", "oval"],
    [3, "green", "outlined", "diamond"],
    [3, "red", "outlined", "diamond"],
    [2, "purple", "outlined", "oval"],
    [1, "red", "outlined", "oval"],
    [1, "purple", "solid", "oval"],
    [3, "green", "striped", "squiggle"],
    [3, "green", "solid", "oval"],
    [3, "purple", "solid", "oval"],
    [1, "red", "striped", "oval"],
    [1, "red", "outlined", "squiggle"],
    [1, "green", "striped", "diamond"],
  ],
  [
    [2, "purple", "solid", "oval"],
    [3, "green", "outlined", "squiggle"],
    [2, "purple", "outlined", "squiggle"],
    [3, "red", "striped", "squiggle"],
    [2, "green", "outlined", "diamond"],
    [3, "green", "striped", "diamond"],
    [3, "red", "solid", "diamond"],
    [2, "purple", "striped", "squiggle"],
    [2, "red", "striped", "squiggle"],
    [1, "green", "solid", "squiggle"],
    [1, "purple", "solid", "oval"],
    [3, "purple", "outlined", "diamond"],
  ],
  [
    [1, "red", "solid", "diamond"],
    [2, "green", "outlined", "oval"],
    [2, "green", "striped", "oval"],
    [3, "green", "solid", "squiggle"],
    [3, "green", "solid", "oval"],
    [3, "red", "striped", "oval"],
    [3, "purple", "outlined", "oval"],
    [2, "red", "solid", "oval"],
    [3, "green", "outlined", "oval"],
    [1, "green", "striped", "oval"],
    [1, "red", "outlined", "oval"],
    [3, "green", "solid", "diamond"],
  ],
  [
    [2, "purple", "solid", "squiggle"],
    [2, "green", "outlined", "oval"],
    [1, "purple", "solid", "squiggle"],
    [1, "green", "striped", "diamond"],
    [1, "purple", "outlined", "squiggle"],
    [1, "purple", "outlined", "oval"],
    [1, "purple", "striped", "diamond"],
    [1, "green", "striped", "squiggle"],
    [1, "red", "solid", "diamond"],
    [3, "red", "outlined", "squiggle"],
    [3, "green", "solid", "squiggle"],
    [2, "red", "striped", "diamond"],
  ],
  [
    [2, "purple", "solid", "oval"],
    [3, "red", "solid", "diamond"],
    [3, "purple", "striped", "oval"],
    [3, "purple", "outlined", "diamond"],
    [2, "purple", "striped", "diamond"],
    [1, "green", "solid", "squiggle"],
    [1, "green", "striped", "diamond"],
    [3, "green", "striped", "squiggle"],
    [3, "red", "striped", "diamond"],
    [1, "purple", "solid", "diamond"],
    [1, "green", "solid", "oval"],
    [1, "red", "outlined", "diamond"],
  ],
  [
    [1, "red", "outlined", "squiggle"],
    [1, "red", "outlined", "diamond"],
    [3, "purple", "outlined", "squiggle"],
    [3, "purple", "solid", "oval"],
    [1, "purple", "solid", "squiggle"],
    [3, "purple", "striped", "diamond"],
    [2, "red", "outlined", "oval"],
    [3, "red", "outlined", "diamond"],
    [1, "green", "striped", "oval"],
    [2, "purple", "striped", "squiggle"],
    [2, "green", "striped", "squiggle"],
    [1, "purple", "striped", "diamond"],
  ],
  [
    [3, "red", "striped", "diamond"],
    [2, "green", "striped", "diamond"],
    [2, "purple", "outlined", "oval"],
    [3, "red", "striped", "oval"],
    [2, "red", "striped", "diamond"],
    [1, "red", "solid", "diamond"],
    [1, "red", "striped", "squiggle"],
    [2, "red", "outlined", "squiggle"],
    [2, "purple", "striped", "diamond"],
    [1, "purple", "solid", "oval"],
    [3, "green", "striped", "diamond"],
    [3, "purple", "striped", "oval"],
  ],
  [
    [1, "green", "solid", "squiggle"],
    [2, "red", "striped", "squiggle"],
    [1, "purple", "striped", "diamond"],
    [2, "red", "striped", "oval"],
    [1, "red", "outlined", "oval"],
    [3, "red", "solid", "diamond"],
    [3, "red", "striped", "oval"],
    [2, "purple", "outlined", "squiggle"],
    [2, "purple", "solid", "oval"],
    [2, "green", "outlined", "oval"],
    [3, "green", "solid", "diamond"],
    [2, "green", "outlined", "diamond"],
  ],
  [
    [3, "purple", "striped", "oval"],
    [2, "green", "outlined", "squiggle"],
    [3, "red", "striped", "squiggle"],
    [2, "green", "solid", "squiggle"],
    [2, "purple", "outlined", "diamond"],
    [1, "purple", "solid", "squiggle"],
    [3, "green", "solid", "oval"],
    [1, "green", "outlined", "oval"],
    [2, "purple", "solid", "diamond"],
    [1, "red", "outlined", "oval"],
    [1, "purple", "striped", "diamond"],
    [3, "purple", "outlined", "diamond"],
  ],
  [
    [3, "green", "outlined", "diamond"],
    [2, "green", "solid", "oval"],
    [1, "green", "striped", "squiggle"],
    [3, "green", "striped", "diamond"],
    [3, "purple", "striped", "diamond"],
    [3, "red", "outlined", "squiggle"],
    [2, "purple", "outlined", "diamond"],
    [3, "green", "solid", "diamond"],
    [3, "purple", "outlined", "squiggle"],
    [2, "red", "striped", "squiggle"],
    [1, "green", "solid", "squiggle"],
    [1, "purple", "striped", "diamond"],
  ],
  [
    [2, "purple", "striped", "oval"],
    [2, "red", "solid", "oval"],
    [2, "purple", "striped", "squiggle"],
    [3, "purple", "solid", "squiggle"],
    [1, "purple", "striped", "diamond"],
    [2, "green", "solid", "squiggle"],
    [2, "red", "solid", "squiggle"],
    [1, "purple", "outlined", "oval"],
    [3, "red", "solid", "squiggle"],
    [1, "red", "solid", "squiggle"],
    [2, "purple", "striped", "diamond"],
    [1, "purple", "solid", "squiggle"],
  ],
  [
    [2, "purple", "solid", "squiggle"],
    [1, "red", "outlined", "diamond"],
    [2, "purple", "outlined", "squiggle"],
    [3, "purple", "outlined", "diamond"],
    [1, "purple", "striped", "diamond"],
    [3, "purple", "outlined", "oval"],
    [3, "green", "outlined", "squiggle"],
    [1, "green", "striped", "diamond"],
    [3, "red", "outlined", "oval"],
    [2, "green", "striped", "oval"],
    [2, "purple", "outlined", "oval"],
    [1, "purple", "outlined", "oval"],
  ],
  [
    [3, "green", "outlined", "diamond"],
    [1, "red", "solid", "oval"],
    [2, "purple", "striped", "oval"],
    [3, "red", "outlined", "squiggle"],
    [3, "purple", "outlined", "oval"],
    [3, "green", "outlined", "squiggle"],
    [1, "purple", "outlined", "squiggle"],
    [2, "red", "outlined", "squiggle"],
    [3, "red", "striped", "oval"],
    [1, "green", "solid", "oval"],
    [2, "green", "solid", "diamond"],
    [1, "green", "striped", "diamond"],
  ],
  [
    [3, "green", "striped", "oval"],
    [2, "red", "solid", "diamond"],
    [1, "green", "solid", "oval"],
    [1, "purple", "striped", "squiggle"],
    [3, "green", "outlined", "squiggle"],
    [1, "red", "outlined", "diamond"],
    [3, "green", "solid", "diamond"],
    [2, "red", "striped", "diamond"],
    [2, "green", "striped", "squiggle"],
    [2, "purple", "solid", "squiggle"],
    [1, "red", "striped", "diamond"],
    [1, "purple", "outlined", "squiggle"],
  ],
  [
    [1, "purple", "outlined", "squiggle"],
    [3, "green", "solid", "oval"],
    [2, "green", "striped", "squiggle"],
    [1, "red", "solid", "squiggle"],
    [2, "green", "outlined", "oval"],
    [2, "purple", "striped", "oval"],
    [1, "red", "outlined", "oval"],
    [2, "purple", "outlined", "squiggle"],
    [3, "purple", "solid", "diamond"],
    [3, "red", "outlined", "diamond"],
    [3, "green", "outlined", "diamond"],
    [1, "red", "solid", "diamond"],
  ],
  [
    [3, "red", "striped", "diamond"],
    [1, "green", "striped", "squiggle"],
    [2, "purple", "outlined", "oval"],
    [3, "green", "striped", "oval"],
    [2, "green", "solid", "squiggle"],
    [3, "red", "solid", "oval"],
    [3, "green", "solid", "oval"],
    [3, "red", "outlined", "diamond"],
    [1, "red", "solid", "diamond"],
    [3, "red", "solid", "diamond"],
    [3, "purple", "solid", "oval"],
    [2, "red", "striped", "diamond"],
  ],
  [
    [3, "red", "striped", "squiggle"],
    [3, "purple", "outlined", "diamond"],
    [2, "green", "striped", "oval"],
    [3, "purple", "outlined", "squiggle"],
    [2, "purple", "striped", "diamond"],
    [1, "red", "outlined", "squiggle"],
    [1, "purple", "solid", "oval"],
    [3, "green", "striped", "diamond"],
    [2, "purple", "striped", "oval"],
    [1, "purple", "striped", "diamond"],
    [1, "purple", "solid", "diamond"],
    [1, "green", "striped", "diamond"],
  ],
  [
    [1, "red", "outlined", "diamond"],
    [2, "purple", "solid", "oval"],
    [3, "red", "striped", "squiggle"],
    [1, "green", "outlined", "diamond"],
    [3, "purple", "outlined", "squiggle"],
    [1, "green", "outlined", "squiggle"],
    [1, "green", "striped", "diamond"],
    [1, "purple", "solid", "diamond"],
    [3, "green", "solid", "squiggle"],
    [1, "purple", "outlined", "diamond"],
    [1, "purple", "striped", "diamond"],
    [3, "purple", "outlined", "diamond"],
  ],
  [
    [1, "red", "outlined", "squiggle"],
    [2, "purple", "striped", "diamond"],
    [3, "green", "solid", "diamond"],
    [3, "green", "outlined", "squiggle"],
    [2, "red", "striped", "diamond"],
    [3, "green", "striped", "oval"],
    [1, "purple", "outlined", "diamond"],
    [2, "green", "outlined", "oval"],
    [1, "green", "striped", "squiggle"],
    [3, "purple", "solid", "oval"],
    [1, "purple", "outlined", "squiggle"],
    [1, "red", "solid", "oval"],
  ],
  [
    [3, "green", "striped", "squiggle"],
    [1, "green", "outlined", "oval"],
    [1, "red", "striped", "squiggle"],
    [2, "green", "solid", "oval"],
    [1, "red", "solid", "oval"],
    [2, "purple", "outlined", "oval"],
    [3, "green", "outlined", "squiggle"],
    [2, "green", "outlined", "diamond"],
    [2, "purple", "striped", "squiggle"],
    [3, "red", "solid", "oval"],
    [1, "red", "outlined", "diamond"],
    [3, "purple", "solid", "oval"],
  ],
  [
    [1, "purple", "outlined", "diamond"],
    [1, "purple", "solid", "diamond"],
    [3, "green", "striped", "squiggle"],
    [2, "purple", "solid", "squiggle"],
    [2, "green", "outlined", "diamond"],
    [1, "green", "solid", "oval"],
    [1, "red", "outlined", "oval"],
    [3, "red", "solid", "diamond"],
    [1, "purple", "striped", "oval"],
    [3, "red", "striped", "oval"],
    [3, "red", "outlined", "diamond"],
    [1, "purple", "striped", "diamond"],
  ],
  [
    [1, "purple", "outlined", "oval"],
    [2, "green", "outlined", "squiggle"],
    [1, "green", "outlined", "squiggle"],
    [1, "red", "outlined", "oval"],
    [2, "red", "solid", "oval"],
    [3, "purple", "outlined", "squiggle"],
    [1, "purple", "solid", "squiggle"],
    [1, "purple", "striped", "diamond"],
    [2, "green", "solid", "squiggle"],
    [3, "purple", "striped", "diamond"],
    [1, "green", "striped", "oval"],
    [1, "red", "solid", "oval"],
  ],
  [
    [2, "green", "outlined", "squiggle"],
    [3, "purple", "striped", "oval"],
    [3, "green", "striped", "squiggle"],
    [3, "green", "outlined", "oval"],
    [2, "green", "solid", "oval"],
    [1, "purple", "outlined", "squiggle"],
    [3, "red", "striped", "oval"],
    [2, "purple", "solid", "diamond"],
    [3, "red", "outlined", "diamond"],
    [1, "green", "outlined", "squiggle"],
    [1, "purple", "outlined", "oval"],
    [3, "red", "striped", "diamond"],
  ],
  [
    [2, "purple", "solid", "squiggle"],
    [1, "purple", "solid", "oval"],
    [2, "red", "solid", "oval"],
    [1, "green", "outlined", "diamond"],
    [1, "green", "solid", "oval"],
    [2, "red", "outlined", "squiggle"],
    [3, "purple", "solid", "oval"],
    [1, "red", "solid", "oval"],
    [2, "red", "outlined", "oval"],
    [3, "red", "striped", "oval"],
    [1, "green", "striped", "diamond"],
    [3, "red", "solid", "oval"],
  ],
];

function shuffle<T>(arr: T[], random: () => number) {
  let currentIndex = arr.length;

  // While there remain elements to shuffle...
  while (currentIndex != 0) {
    // Pick a remaining element...
    const randomIndex = Math.floor(random() * currentIndex);
    currentIndex--;

    // And swap it with the current element.
    [arr[currentIndex], arr[randomIndex]] = [arr[randomIndex], arr[currentIndex]];
  }

  return arr;
}

function getCardsFor(date: string) {
  const random = seed(date);

  const cards = COMBINATIONS[Math.floor(random() * COMBINATIONS.length)];
  shuffle(cards, random);

  return cards.map(
    ([count, color, pattern, shape]) => new CardDetails(count, color, pattern, shape),
  );
}

const today = new Intl.DateTimeFormat("en-US").format(new Date());
export const cards = getCardsFor(today);
